student_management_system/urls.py
# student_management_system/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('students.urls')),
]

students/urls.py
# students/urls.py
from django.urls import path

from . import views
from .views import index, student_list, login, add_course, course_type, course_list, add_student, delete_course_type, \
    edit_course, edit_course_type, create_course_type, student_courses_view, query_student_courses_view, \
    enrollment_view, choose_courses_view, save_choose_courses, delete_course

urlpatterns = [
    path('student_list/', student_list, name='student_list'),
    path('login/', login, name='login'),
    path('add_course/', add_course, name='add_course'),
    path('add_student/', add_student, name='add_student'),
    path('course_type/', course_type, name='course_type'),
    path('course_list/', course_list, name='course_list'),
    path('index/', index, name='index'),
    path('delete_course_type/', delete_course_type, name='delete_course_type'),
    path('delete_course/', delete_course, name='delete_course'),
    path('edit_course/<int:course_no>/', edit_course, name='edit_course'),
    path('edit_course_type/<int:id>/', edit_course_type, name='edit_course_type'),
    path('create_course_type/', create_course_type, name='create_course_type'),
    path('student_courses/<int:student_roll_number>/', student_courses_view, name='student_courses_view'),
    path('query_student_courses/', query_student_courses_view, name='query_student_courses'),
    path('enrollment/', enrollment_view, name='enrollment_view'),
    path('choose_courses_view/',choose_courses_view,name='choose_courses_view'),
    path('save_courses_view/', save_choose_courses, name='save_choose_courses'),
]

students/models.py
from django.db import models

class User(models.Model):
    user_number = models.CharField(max_length=20)
    user_password = models.CharField(max_length=100)
    user_name = models.CharField(max_length=100)
    class Meta:
        db_table = 'students_user'
    def __str__(self):
        return self.user_number
class Course_Type(models.Model):
    id = models.BigAutoField(primary_key=True)
    type_name = models.CharField(max_length=255,verbose_name='课程类型')
    class Meta:
        db_table = 'students_course_type'
    def __str__(self):
        return self.id
class Course(models.Model):
    course_no = models.AutoField(primary_key=True,verbose_name='课程编号',unique=True)
    course_name = models.CharField(max_length=255, verbose_name='课程名称')
    course_hours = models.IntegerField(verbose_name='课程学时')
    type_id = models.IntegerField(verbose_name='类型')
    course_status = models.CharField(max_length=20, verbose_name='课程状态')
    course_reqs = models.CharField(max_length=20, blank=True, null=True, verbose_name='需求')
    course_point = models.FloatField(verbose_name='课程学分')
    course_memo = models.TextField(blank=True, null=True, verbose_name='课程备注')
    course_textbook_pic = models.URLField(blank=True, null=True, verbose_name='课程图片URL')
    class Meta:
        db_table = 'course'
    def __str__(self):
        return f"{self.course_no}"

class Student(models.Model):
    GENDER_CHOICES = {
        "1": "男",
        "2": "女",
        # 可以根据需要添加其他性别选项
    }

    class Meta:
        db_table = 'students_student'

    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=100, verbose_name='名字')
    roll_number = models.CharField(max_length=20, unique=True, null=True, verbose_name='学号')
    age = models.IntegerField(verbose_name='年龄')
    sex = models.CharField(max_length=1, choices=[("1", "男"), ("2", "女")], verbose_name='性别')
    class_name = models.CharField(max_length=255, verbose_name='班级')

    def __str__(self):
        return self.name

class Enrollment(models.Model):
    enrollment_id = models.AutoField(primary_key=True, verbose_name='选课编号', unique=True)
    roll_number = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='enrollments', verbose_name='学生')
    course_no = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='enrollments', verbose_name='课程')
    enrollment_date = models.DateField(auto_now_add=True, verbose_name='选课日期')
    class Meta:
        unique_together = ('roll_number', 'course_no')
        db_table = 'enrollment'
    def __str__(self):
        return f"Enrollment ID: {self.enrollment_id}, Student: {self.roll_number.name}, Course: {self.course_no.course_name}"

students/forms.py
# forms.py
from django import forms
from .models import Course, Course_Type
from .models import Student
class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_name', 'course_hours', 'type_id', 'course_status', 'course_reqs', 'course_point', 'course_memo', 'course_textbook_pic']
        # 添加一个隐藏的课程编号字段
        course_no = forms.IntegerField(widget=forms.HiddenInput())


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'roll_number', 'age', 'sex', 'class_name']


class CourseTypeForm(forms.ModelForm):
    class Meta:
        model = Course_Type
        fields = ['type_name']

students/views.py
from django.contrib.auth.decorators import login_required
from django.db import models

# students/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_protect, csrf_exempt

from .models import Student, User, Course_Type, Course, Enrollment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CourseForm, StudentForm, CourseTypeForm
from django.http import HttpResponse, JsonResponse
from django.contrib import messages


def login(request):
    if request.method == 'POST':
        usernumber = request.POST.get('username')
        password = request.POST.get('password')

        user = User.objects.filter(user_number=usernumber).first()
        if user and user.user_password == password:
            return redirect('index')
        else:
            return render(request, 'students/login.html')
    else:
        return render(request, 'students/login.html')

def add_course(request):
    if request.method == 'POST':
        form = CourseForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, '课程添加成功！')  # 添加成功消息
            return redirect('add_course')
    else:
        form = CourseForm()
    response = render(request, 'students/add_course.html', {'form': form})
    response['X-Frame-Options'] = 'ALLOWALL'
    return response

@csrf_protect
def delete_course(request):
    if request.method == 'POST':
        course_no = request.POST.get('course_no')
        # 执行删除逻辑
        try:
            course = Course.objects.get(course_no=course_no)
            course.delete()
            return JsonResponse({'message': 'Course deleted successfully'})
        except Course.DoesNotExist:
            return JsonResponse({'message': 'Course not found'}, status=404)
    return JsonResponse({'message': 'Invalid request method'}, status=400)

def edit_course(request, course_no):
    course = get_object_or_404(Course, course_no=course_no)
    if request.method == 'POST':
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return redirect('course_list')
    else:
        form = CourseForm(instance=course)
    return render(request, 'students/edit_course.html', {'form': form, 'course': course})


def course_list(request):
    query = request.GET.get('query', '')
    courses = Course.objects.all()
    if query:
        courses = Course.objects.filter(course_name__icontains=query)
    # 分页处理
    paginated_courses = paginator(request, courses)
    response = render(request, 'students/course_list.html', {'courses': paginated_courses, 'query': query})

    response['X-Frame-Options'] = 'ALLOWALL'

    return response

def student_list(request):
    query = request.GET.get('query', '')
    students = Student.objects.all()
    if query:
        students = Student.objects.filter( name__icontains=query)

    paginated_students = paginator(request, students)
    # 创建 HttpResponse 对象
    response = render(request, 'students/student_list.html', {'students': paginated_students})
    # 设置 X-Frame-Options 头为 'ALLOWALL'
    response['X-Frame-Options'] = 'ALLOWALL'
    return response




def course_type(request):
    courses = Course_Type.objects.all()
    paginated_courses = paginator(request, courses)
    # 创建 HttpResponse 对 象
    response = render(request, 'students/course_type.html', {'courses': paginated_courses})
    # 设置 X-Frame-Options 头为 'ALLOWALL'
    response['X-Frame-Options'] = 'ALLOWALL'
    return response


def paginator(request, data):
    per_page = 3
    paginator = Paginator(data, per_page)
    page = request.GET.get('page')
    try:
        paginated_data = paginator.page(page)
    except PageNotAnInteger:
        paginated_data = paginator.page(1)
    except EmptyPage:
        paginated_data = paginator.page(paginator.num_pages)
    return paginated_data




@csrf_protect
def delete_course_type(request):
    if request.method == 'POST':
        course_type_id = request.POST.get('course_type_id')
        # 执行删除逻辑
        try:
            course_type = Course_Type.objects.get(id=course_type_id)
            course_type.delete()
            return JsonResponse({'message': 'Course type deleted successfully'})
        except Course_Type.DoesNotExist:
            return JsonResponse({'message': 'Course type not found'}, status=404)
    return JsonResponse({'message': 'Invalid request method'}, status=400)


def edit_course_type(request, id):
    course_type = get_object_or_404(Course_Type, id=id)
    if request.method == 'POST':
        form = CourseTypeForm(request.POST, instance=course_type)
        if form.is_valid():
            form.save()
            return redirect('course_type')
    else:

        form = CourseTypeForm(instance=course_type)

    return render(request, 'students/edit_course_type.html', {'form': form, 'course_type': course_type})

def create_course_type(request):
    if request.method == 'POST':
        form = CourseTypeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('course_type')
    else:
        form = CourseTypeForm()

    return render(request, 'students/create_course_type.html', {'form': form})


def query_student_courses_view(request):

    if request.method == 'POST':
        student_roll_number = request.POST.get('student_roll_number')
        student = get_object_or_404(Student, roll_number=student_roll_number)
        return redirect('student_courses_view', student_roll_number=student.roll_number)
    else:
        return redirect('enrollment_view')


def student_courses_view(request,student_roll_number):
    student = get_object_or_404(Student, roll_number=int(student_roll_number))
    print(student.roll_number)
    enrollments = Enrollment.objects.filter(roll_number_id=student.roll_number)
    courses=[]
    for enrollment in enrollments:
        course_no_id = enrollment.course_no_id
        course = Course.objects.get(course_no=course_no_id)
        courses.append(course)

    contexts = {'student': student, 'enrollments': enrollments, 'course': courses}
    return render(request, 'students/student_courses.html',contexts)


def choose_courses_view(request):
    if request.method == 'POST':
        student_roll_number = request.POST.get('student_roll_number')
        student = get_object_or_404(Student, roll_number=student_roll_number)
        enrollments = Enrollment.objects.filter(roll_number_id=student.roll_number)
        courses = Course.objects.filter(course_status='开课')
        context = {'student': student, 'enrollments': enrollments, 'courses': courses}
        return render(request, 'students/choose_courses.html', context)

@csrf_exempt
def save_choose_courses(request):
    if request.method == 'POST':
        student_roll_number = request.POST.get('student_roll_number')
        course_no = request.POST.get('course_no')
        student = get_object_or_404(Student, roll_number=student_roll_number)
        course = get_object_or_404(Course, course_no=course_no)

        if Enrollment.objects.filter(roll_number=student.roll_number, course_no_id=course.course_no).exists():
            return JsonResponse({'message': '学生已选择该课程'})
        # 创建新的选课记录
        else:
            try:
                enrollment = Enrollment.objects.create(roll_number_id=student.roll_number, course_no_id=course.course_no)
                if enrollment.course_no_id==course.course_no:

                    return JsonResponse({'message': '选课成功'})
            except:
                  print("no")
    return JsonResponse({'message': '无效的请求'})




def add_student(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('student_list')  # 重定向到学生列表页面
    else:
        form = StudentForm()

    return render(request, 'students/add_student.html', {'form': form})

def enrollment_view(request):
    return render(request ,'students/enrollment.html')

def index(request):
    return render(request,'students/index.html')

students/templates/students/add_course.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>添加课程</title>
    <!-- 在这里引入你的样式表文件，如果有的话 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '/form.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>

<h2>添加课程</h2>
{% if messages %}
    {% for message in messages %}
        <div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="successModalLabel">成功消息</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {{ message }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                    </div>
                </div>
            </div>
        </div>

        <script>
            // 在页面加载时显示模态框
            $(document).ready(function () {
                $('#successModal').modal('show');
            });
        </script>
    {% endfor %}
{% endif %}

{% block content %}
    <div class="custom-form-container">
        <form action="{% url 'add_course' %}" method="post" enctype="multipart/form-data" class="custom-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="custom-submit-button">添加课程</button>
        </form>
    </div>
{% endblock %}




</body>
</html>

students/templates/students/add_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Student</title>
</head>
<body>
    <h2>添加学生</h2>
    <form method="post" action="{% url 'add_student' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">提交</button>
    </form>
</body>
</html>

students/templates/students/choose_courses.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static '/table.css' %}">
<h2>可选课程列表</h2>

      <table id="course-table">
    <thead>
        <tr>
            <th>课程名称</th>
            <th>课程学时</th>
            <th>类型编号</th>
            <th>课程状态</th>
            <th>先修条件</th>
            <th>课程学分</th>
            <th>教材图片</th>
            <th>选课</th>
        </tr>
    </thead>
    <tbody>
        {% for course in courses %}
            <tr>
                <td>{{ course.course_name }}</td>
                <td>{{ course.course_hours }}</td>
                <td>{{ course.type_id }}</td>
                <td>{{ course.course_status }}</td>
                <td>{{ course.course_reqs }}</td>
                <td>{{ course.course_point }}</td>
                <td>{% if course.course_textbook_pic %}
                     <img src="{{ course.course_textbook_pic }}"  width="100" height="100" alt="课程图片">
                       {% else %}
                             <p>没有可用的图片</p>
                       {% endif %}
                </td>
                <td><button onclick="selectCourse({{ student.roll_number }}, {{ course.course_no }})">选择课程</button></td>
            </tr>
        {% endfor %}
    </tbody>
</table>


<script>
  function selectCourse(studentRollNumber, courseNo) {
    // 在这里可以添加选择确认的弹窗逻辑
    // 确认后，可以使用 AJAX 请求将选课信息发送到后端处理
    // 注意：这里只是一个示例，实际的实现可能需要更多的细节
      var confirmSelection = confirm('确认选择该课程吗？');

  if (confirmSelection) {

    $.ajax({
      url: '{% url 'save_choose_courses' %}',
      method: 'POST',
      data: {
        'student_roll_number': studentRollNumber,
        'course_no': courseNo,
      },

      success: function(response) {
           if (response.message === '学生已选择该课程') {
                   alert('学生已选择该课程');
       }
           else if (response.message === '选课成功'){
              alert('选课成功！');
             location.reload()}
           else {
               alert("请求错误")
           }
    // 跳转到编辑页面
      },
      error: function() {
        alert('选课失败！');
           location.reload()
      }
    });
  }
  }
</script>

students/templates/students/course_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
     <link rel="stylesheet" type="text/css" href="{% static '/table.css' %}">
       <script src="{% static 'csrftoken.js' %}"></script>
</head>
<body>
<h2>课程</h2>
<div id="content-container">
<div>
<td><a href="{% url 'add_course' %}" >添加课程</a></td>

<form method="get" action="{% url 'course_list' %}">
    <input type="text" name="query" value="{{ query }}">
    <button type="submit">搜索</button>
</form>


<table id="course-table">
    <thead>
        <tr>
            <th>课程编号</th>
            <th>课程名称</th>
            <th>课程学时</th>
            <th>类型编号</th>
            <th>课程状态</th>
            <th>先修条件</th>
            <th>课程学分</th>
            <th>课程备注</th>
            <th>教材图片</th>
            <th>功能</th><th>功能</th>
        </tr>
    </thead>
    <tbody>
        {% for course in courses %}
            <tr>
                <td>{{ course.course_no }}</td>
                <td>{{ course.course_name }}</td>
                <td>{{ course.course_hours }}</td>
                <td>{{ course.type_id }}</td>
                <td>{{ course.course_status }}</td>
                <td>{{ course.course_reqs }}</td>
                <td>{{ course.course_point }}</td>
                <td>{{ course.course_memo }}</td>
                <td>{% if course.course_textbook_pic %}
                     <img src="{{ course.course_textbook_pic }}"  width="100" height="100" alt="课程图片">
                       {% else %}
                             <p>没有可用的图片</p>
                       {% endif %}
                </td>

          <td><a href="#" onclick="editCourse({{ course.course_no }}); return false;">修改</a></td>
<td><a href="#" onclick="deleteCourse({{ course.course_no }}); return false;">删除</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

</div>
<div class="pagination">
    <span class="step-links">
        {% if courses.has_previous %}
            <a href="{% url 'course_list' %}?page=1">&laquo; 首页</a>
            <a href="{% url 'course_list' %}?page={{ courses.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            Page {{ courses.number }} of {{ courses.paginator.num_pages }}.
        </span>

        {% if courses.has_next %}
            <a href="{% url 'course_list' %}?page={{ courses.next_page_number }}">下一页</a>
            <a href="{% url 'course_list' %}?page={{ courses.paginator.num_pages }}">最后一页 &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
<!-- 请确保 jQuery 库已经被引入 -->

<script>
function editCourse(courseNo) {
    // 构建编辑页面的 URL
    var editUrl = '/edit_course/' + courseNo + '/';

    // 跳转到编辑页面
    window.location.href = editUrl;
}


    function deleteCourse(course_no) {
    if (confirm('确认删除？')) {
        // 获取 CSRF 令牌的值
        const csrftoken = getCookie('csrftoken');

        // 使用 AJAX 请求删除记录
        $.ajax({
            url: '{% url "delete_course" %}',
            method: 'POST',
            data: { 'course_no': course_no },
            headers: {
                'X-CSRFToken': csrftoken
            },
            success: function () {
                 alert("删除成功！")
                 location.reload();
            },
            error: function () {
                alert('删除失败！');
            }
        });
    }
}




</script>
</body>
</html>

students/templates/students/course_type.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static '/table.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
   <script src="{% static 'csrftoken.js' %}"></script>
</head>
<body>
<h2>课程类型</h2>
<td><a href="{% url 'create_course_type'  %}">新增</a></td>

<table class="table">
    <thead>
        <tr>
            <th>id</th>
            <th>类型</th>
            <th>操作</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        {% for course_type in courses %}
            <tr>
                <td>{{ course_type.id }}</td>
                <td>{{ course_type.type_name }}</td>
                <td><a href="/edit_course_type/{{ course_type.id }}/">编辑</a></td>
                 <td><a href="#" onclick="deleteCourseType({{ course_type.id }}); return false;">删除</a></td>
            </tr>

        {% endfor %}

    </tbody>
</table>


<div class="pagination">
    <span class="step-links">
        {% if courses.has_previous %}
            <a href="{% url 'course_type' %}?page=1">&laquo; 首页</a>
            <a href="{% url 'course_type' %}?page={{ courses.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            Page {{ courses.number }} of {{ courses.paginator.num_pages }}.
        </span>

        {% if courses.has_next %}
            <a href="{% url 'course_type' %}?page={{ courses.next_page_number }}">下一页</a>
            <a href="{% url 'course_type' %}?page={{ courses.paginator.num_pages }}">最后一页 &raquo;</a>
        {% endif %}
    </span>
</div>

<script>
    function deleteCourseType(courseTypeId) {
    if (confirm('确认删除？')) {
        // 获取 CSRF 令牌的值
        const csrftoken = getCookie('csrftoken');

        // 使用 AJAX 请求删除记录
        $.ajax({
            url: '{% url "delete_course_type" %}',
            method: 'POST',
            data: { 'course_type_id': courseTypeId },
            headers: {
                'X-CSRFToken': csrftoken
            },
            success: function () {
                 alert("删除成功！")
                 location.reload();
            },
            error: function () {
                alert('删除失败！');
            }
        });
    }
}



</script>
</body>
</html>

students/templates/students/create_course_type.html
<form method="post" action="{% url 'create_course_type' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">创建新课程类型</button>
</form>

students/templates/students/edit_course.html
{% block content %}
  <h2>修改课程</h2>
 <!-- 在 edit_course.html 中 -->
<form method="post" action="{% url 'edit_course' course.course_no %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">保存修改</button>
</form>


{% endblock %}

students/templates/students/edit_course_type.html
{% load static %}
<!-- students/templates/students/edit_course_type.html -->

{% block content %}
  <h2>编辑课程类型</h2>
  <form method="post" action="{% url 'edit_course_type' id=course_type.id %}" class="styled-table">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">保存修改</button>
  </form>
{% endblock %}

students/templates/students/enrollment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>学生选课系统</title>
</head>
<body>
    <h1>学生选课系统</h1>

    <!-- 学生列表展示 -->

    <h2>查询学生已选课程</h2>
<form action="{% url 'query_student_courses' %}" method="post">
    {% csrf_token %}
    <label for="student_roll_number">输入学号：</label>
    <input type="text" name="student_roll_number" id="student_roll_number" required>
    <button type="submit">查询</button>
</form>


    <h2>学生选课</h2>
    <form action="{% url 'choose_courses_view' %}" method="post">
    {% csrf_token %}
    <label for="student_roll_number">输入学号：</label>
    <input type="text" name="student_roll_number" id="student_roll_number" required>
    <button type="submit">确认</button>
</form>
    <!-- 其他内容 -->
</body>
</html>

students/templates/students/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>登录页面</title>
     <link rel="stylesheet" href="{% static 'style_login.css' %}">
</head>
<body>
 <div class="box">
     <h2>Login</h2>
  <form action="/login/" method="post">
            {% csrf_token %}
            <div class="input-box">
                <label for="username">账号</label>
                <input type="text" id="username" name="username"/>
            </div>
            <div class="input-box">
                <label for="password">密码</label>
                <input type="password" id="password" name="password"/>
            </div>
            <div class="btn-box">
                <a href="#">忘记密码?</a>
                <div>
                    <button type="submit">登录</button>
                    <button>注册</button>
                </div>
            </div>
        </form>
 </div>
</body>
</html>

students/templates/students/student_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static '/table.css' %}">
</head>
<body>
<h2>学生数据</h2>
<button type="button" onclick="openAddStudentModal()">添加学生</button>

<script>
  function openAddStudentModal() {
    window.location.href = "{% url 'add_student' %}";
  }
</script>

<form method="get" action="{% url 'student_list' %}">
    <input type="text" name="query" value="{{ query }}">
    <button type="submit">搜索</button>
</form>

<table >
    <thead>
        <tr>
            <th>姓名</th>
            <th>学号</th>
            <th>年龄</th>
            <th>性别</th>
            <th>班级</th>
            <th>功能</th>
            <th>功能</th>
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
            <tr>
                <td>{{ student.name }}</td>
                <td>{{ student.roll_number }}</td>
                <td>{{ student.age }}</td>
                <td>{{ student.get_sex_display }}</td>
                <td>{{ student.class_name }}</td>
            <td><a>删除</a></td>
                <td><a>修改</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="pagination">
    <span class="step-links">
        {% if students.has_previous %}
            <a href="{% url 'student_list' %}?page=1">&laquo; 首页</a>
            <a href="{% url 'student_list' %}?page={{ students.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            Page {{ students.number }} of {{ students.paginator.num_pages }}.
        </span>

        {% if students.has_next %}
            <a href="{% url 'student_list' %}?page={{ students.next_page_number }}">下一页</a>
            <a href="{% url 'student_list' %}?page={{ students.paginator.num_pages }}">最后一页 &raquo;</a>
        {% endif %}
    </span>
</div>

</body>
</html>